version: '3'

services:
 mongo-db:
  container_name: mongo-db
  image: mongo
  ports:
   - 27017
  volumes:
   - ./env/mongo-db:/data/db
  environment:
   PORT: 27017
 api-server:
  container_name: api-server
  build: 
    context: ./
    dockerfile: DockerfileNode
  ports:
    - "4000:4000"
  volumes:
    - ./api-server:/usr/src/app/
  links:
    - mongo-db
  environment:
   NODE_ENV: 'development'
   MONGO_URL: mongodb://mongo-db:27017
   PORT: 3000